// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBReEuOqnYIwbZZFZRKQbq02h8cUd2KuZ8',
    appId: '1:609815355166:web:89a85c11a408e4d5d0730f',
    messagingSenderId: '609815355166',
    projectId: 'uneed-a722e',
    authDomain: 'uneed-a722e.firebaseapp.com',
    storageBucket: 'uneed-a722e.appspot.com',
    measurementId: 'G-JM8EXNRTKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI16T-Rhe8ybMH669Y_068d1Ha5_mpwEg',
    appId: '1:609815355166:android:73a3cc56392f1eb7d0730f',
    messagingSenderId: '609815355166',
    projectId: 'uneed-a722e',
    storageBucket: 'uneed-a722e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOeCTb7J5jATyhXpIQKzgkaCkvmL3_L3w',
    appId: '1:609815355166:ios:8ef1854c43fe673fd0730f',
    messagingSenderId: '609815355166',
    projectId: 'uneed-a722e',
    storageBucket: 'uneed-a722e.appspot.com',
    androidClientId: '609815355166-jpnvn6ct6ss1a3kq8dhu07g37dmrmiao.apps.googleusercontent.com',
    iosClientId: '609815355166-qcea6jf6ijbh1895b002i26l0kl1ukji.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
